### ISSUE TITLE
New profile

### ISSUE THREAD

**Issue by gvsro** [WaeCo/node-bluez#1]
After digging the code I found out that the serial profile is hard coded and making a new profile is kinda hard. Can you point me in the right direction?
I want to interface the AVRCP. I found the uuids for the Target and Remote (AVRCPT, AVRCPR) and made a simple AVRCPprofile.js
```
const EventEmitter = require('events').EventEmitter;
const Profile = require('./Profile');
const RawFdSocket = require('./RawFdSocket');


class AVRCPTProfile extends Profile {

    constructor(bluez, DBusObject, listener) {
        super(bluez, DBusObject);
        this.listener = listener;
    }

    get uuid() {
        return AVRCPTProfile.uuid;
    }

    get path(){
        console.log('PATH:',this.bluez.getDevice(devicePath));
        return this.bluez.getDevice(devicePath);

    }

    NewConnection(devicePath, fd, options, callback) {
        this.bluez.getDevice(devicePath).then((device) => {
            this.listener(device, new RawFdSocket(fd, {
                encoding: 'utf8'
            }));
    
            callback();
        }).catch((err)=>{
            callback(err);
        })
    }
}

AVRCPTProfile.uuid = "0000110c-0000-1000-8000-00805f9b34fb";

module.exports = AVRCPTProfile;

// #define AVRCP_REMOTE_UUID	"0000110e-0000-1000-8000-00805f9b34fb"
// #define AVRCP_TARGET_UUID	"0000110c-0000-1000-8000-00805f9b34fb"
```
and using it like this 
```
...

  await device.ConnectProfile(AVRCPProfile).catch((err)=>{
        console.error("Error while connection to device " + address + ": " + err.message);
    });

...

  await bluetooth.registerProfile(AVRCPProfile);
```

And i get this error code 

```
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at Promise (/home/xed/nodeWorkSpace/node_modules/bluez/lib/Bluez.js:162:69)
    at new Promise (<anonymous>)
    at Bluez.registerProfile (/home/xed/nodeWorkSpace/node_modules/bluez/lib/Bluez.js:161:16)
    at bluetooth.init.then (/home/xed/nodeWorkSpace/index.js:33:21)
    at <anonymous>
```

**Comment by WaeCo** [comment]
The API of this lib based on the DBus API of bluez.
Its still in early stages so some convinieze funktionality is missing.

To register a new Profile try:
```
const obj = bluetooth.getUserServiceObject();
const profile = new AVRCPProfile(bluetooth, obj, listener);
await bluetooth.registerProfile(profile, {});
```

Then to connect your Profile:
```
await device.ConnectProfile(AVRCPProfile.uuid)
```

**Comment by patrick246** [comment]
BlueZ already exposes AVRCP functionality on it's DBus interface. You probably don't need to implement your own profile. I was able to control playback just by calling the respective functions on the interface.
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/media-api.txt
