### ISSUE TITLE
TypeError: this._interface.CancelPairing is not a function

### ISSUE THREAD

**Issue by ThomasHalwax** [WaeCo/node-bluez#13]
Hi,

I'm using node-bluez on a RPi Compute Module 3+ with bluez v5.48 and nodejs v10.16.

After initializing and waiting for the adapter my code calls ```SetDicoveryFilter``` which immediately throws an error ```TypeError: this._interface.CancelPairing is not a function```.

```javascript
    // initialization done 
    const adapter = await bluetooth.getAdapter('hci0')
    await adapter.SetDiscoveryFilter({
        'Transport': 'le',
        'DuplicateData': true
     })
```

Here's the error message:
```bash
    TypeError: this._interface.CancelPairing is not a function
      at SetDiscoveryFilter.Promise (/usr/src/app/node_modules/bluez/lib/Adapter.js:170:29)
      at new Promise (<anonymous>)
      at Adapter.SetDiscoveryFilter (/usr/src/app/node_modules/bluez/lib/Adapter.js:169:16)
      at bluetooth.init.then (/usr/src/app/index.js:48:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Thank you for your help!
Thomas

**Comment by WaeCo** [comment]
Thanks for the catch. Should be fixed now

**Comment by ThomasHalwax** [comment]
Thank you for your quick response, the function call does not throw an error anymore!

Thomas
