### ISSUE TITLE
Possible Memory Leak after device removal

### ISSUE THREAD

**Issue by Vishal8523** [WaeCo/node-bluez#27]
When the bluetooth device is removed using the **adapter.RemoveDevice()** API call, suspect that the event listeners on the device remains. So, to avoid the build up of event listeners, the statement **device.removeAllListeners("PropertiesChanged")** and **device.removeAllListeners("removeListener")** is also executed as well.

However, the below issue appears after a some time:
```
(node:530) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 removeListener listeners added. Use emitter.setMaxListeners() to increase limit
(node:530) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 PropertiesChanged listeners added. Use emitter.setMaxListeners() to increase limit
(node:530) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 PropertiesChanged listeners added. Use emitter.setMaxListeners() to increase limit
```

The scenario is to remove unwanted devices from accumulating in the Bluez Cache.

NOTE: Even if the listeners are not removed while removing the device then also the above warning appears.

Appreciate your help in this regards.

**Comment by WaeCo** [comment]
Can you please try dbus-next branch and see if the issue persists?
```bash
npm install git+https://github.com/WaeCo/node-bluez#dbus-next bluetooth-socket
```

**Comment by Vishal8523** [comment]
@WaeCo : Any workarounds using the dbus library ?
How can one avoid these memory leaks ?

**Comment by Vishal8523** [comment]
Upon investigating further, below is the probable root cause for the memory leak.

```
stack: 'MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 
11 removeListener listeners added. Use emitter.setMaxListeners() to increase limit
at _addListener (events.js:280:19)\n    at module.exports.addListener (events.js:297:10)
at Device.DbusInterfaceBase.on (/home/ubuntu/node-bluez/lib/DbusInterfaceBase.js:33:33)
at emitTwo (events.js:126:13)\n    at Device.emit (events.js:214:7)
at _addListener (events.js:249:14)\n    at Device.addListener (events.js:297:10)
at new DbusInterfaceBase (/home/ubuntu/node-bluez/lib/DbusInterfaceBase.js:36:14)
at new Device (/home/ubuntu/node-bluez/lib/Device.js:4:1)
at Bluez.getInterfaceInstance (/home/ubuntu/node-bluez/lib/Bluez.js:318:31)',
```
Appreciate your help.

**Comment by WaeCo** [comment]
You you provide an example that produces this issue?

**Comment by Vishal8523** [comment]
Below is the code used to reproduce the memory leak issue:

```
var async = require('async');
var Bluez = require('./node-bluez');
var bluetooth = new Bluez();

var deviceList = [];
var bleAdapter;

function updateDeviceList(address, properties) {
    for (let device of deviceList) {
        if (device.address === address && (properties.RSSI || properties.TxPower)) {
            device.RSSI_Info = properties.RSSI;
            device.txPower = properties.TxPower;
        }
    }
}

function clearBluezCache() {
    return new Promise(function (resolve) {
        async.eachSeries(unwantedDevices, function (address, next) {
            bluetooth.getDevice(address).then((device) => {
                device.removeAllListeners();
                bleAdapter.RemoveDevice(device).then(() => {
                    console.info('Removed device: ', address, ' from cache');
                    next();
                }).catch(() => {
                    console.info('Error in removing device: ', address, ' from cache');
                    next();
                });
            }).catch(() => {
                console.info('Cannot Fetch Device: ', address);
                next();
            });
        }, function () {
            resolve();
        });
    });
}

bluetooth.on('device', (address, props) => {
    bluetooth.getDevice(address).then((device) => {
        if (device) {
            if ('function' === typeof device.ManufacturerData) {
                device.ManufacturerData().then((manufacturerAD) => {
                    if (manufacturerAD && parseInt(Object.keys(manufacturerAD)[0]).toString(16) === '445') {
                        if (props.Name === 'SAMSUNG') {
                            let bleDev = {};
                            bleDev.address = address;
                            bleDev.name = props.Name;
                            bleDev.RSSI_Info = props.RSSI;
                            bleDev.txPower = props.TxPower;

                            console.info('Device Found: ', bleDev);
                            deviceList.push(bleDev);
                        }
                        else {
                            console.info('Non Supported Variant for Device: ', address, variant);
                            unwantedDevices.push(address);
                        }
                    }
                    else {
                        console.info('Non Supported/Non Siemens Device: ', address);
                        unwantedDevices.push(address);
                    }
                }).catch(() => {
                    console.info('No Manufacturer Data: ', address);
                    unwantedDevices.push(address);
                });
            }

            device.on('PropertiesChanged', (chgProps) => {
                console.info('[CHG] Device: ', address, chgProps);
                updateDeviceList(address.toString(), chgProps);
                if (chgProps.Connected !== undefined && chgProps.Connected === false) {
                    device.Disconnect().then(() => {
                        console.info('[CHG] Device: ', address, ' removed');
                    }).catch(() => {
                        console.info('[CHG] Device: ', address, ' removed error');
                    });
                }
            });
        }
    }).catch(() => {
        console.info('Cannot Fetch Device: ', address);
    });
});

function bluetoothScan(adapter) {
    return new Promise(function (resolve, reject) {
        adapter.StartDiscovery().then(() => {
            console.info('Scan Started. Discovering Near by devices...');
            unwantedDevices = [];
            setTimeout(() => {
                adapter.StopDiscovery().then(() => {
                    console.info('Scan Stopped');
                    clearBluezCache().then(() => {
                        console.info('Successfully removed unwanted devices in scan');
                        resolve();
                    }).catch(() => {
                        console.info('Error in removing unwanted devices in scan');
                        resolve();
                    });
                }).catch(() => {
                    console.info('Error to stop scan');
                    reject();
                });
            }, 15000);
        }).catch(() => {
            console.info('Error to start scan');
            reject();
        });
    });
}

function bluetoothInit() {
    bluetooth.init().then(() => {
        bluetooth.getAdapter('hci0').then((adapter) => {
            bleAdapter = adapter;
            console.info('Bluetooth Adapter Found');
            setInterval(() => {
                bluetoothScan(adapter);
            }, 30000);
        }).catch((adapterFetchError) => {
            console.info('Bluetooth Adapter Not Found: ', adapterFetchError);
        });
    }).catch((initError) => {
        console.info('Error in initializing Dbus and Interfaces: ', initError);
    });
}

bluetoothInit();
```

This code scans the devices every 30 seconds and removes unwanted devices from the bluez cache and removes its associated listeners.

Request you to point out the issue with this code. Your help is appreciated.

**Comment by WaeCo** [comment]
Thanks, i found the issue. 
`PropertiesChanged` listeners where not unregistered correctly in this case.
However in your code, do not use `device.removeAllListeners();` since this will also remove internal listeners and break thinks.
Change this line to `device.removeAllListeners("PropertiesChanged");` to remove only listeners registered by your application.

Please try current master to see if its fixed for you.

**Comment by Vishal8523** [comment]
@WaeCo : Thanks so much for the quick fix. I tested for 6 hours, so far working fine.
