### ISSUE TITLE
Install fails on Node 10.10

### ISSUE THREAD

**Issue by diginfo** [WaeCo/node-bluez#6]
Hi;

Install fails on Node 10.10, not sure if it is version related ???

```
/root/.node-gyp/10.10.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/root/.node-gyp/10.10.0/include/node/v8.h:9496:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
make: *** [dbus.target.mk:122: Release/obj.target/dbus/src/dbus.o] Error 1
make: Leaving directory '/usr/share/nodejs/nwjs-33-sdk/app/node_modules/dbus/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.69-1-lts
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/share/nodejs/nwjs-33-sdk/app/node_modules/dbus
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dbus@1.0.3 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dbus@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-18T05_14_18_575Z-debug.log
```

**Comment by WaeCo** [comment]
Could you please post to full log.
This error might be related to dbus.

**Comment by woodencatty** [comment]
it works at node v8.11.3..
dunno why, but it happens.

**Comment by yannickadam** [comment]
I only tried it on Node12, but I guess that PR #10 should fix this issue.

**Comment by WaeCo** [comment]
I guess it is fixed
